### ISSUE TITLE
Missing HTML form for Staticman

### ISSUE THREAD

**Issue by VincentTam** [thisHermit/thisHermit.github.io#15]
For a sample HTML form, you may view
https://staticman.net/docs/#step-3-hook-up-your-forms.

**Comment by thisHermit** [comment]
Unable to fix the error at the moment. Adding Screenshots for future reference. Migrated this to a new branch 5abc49aa68b5f0b9cded9982d446bf1b5cd7177d. 

Maybe Disqus is not such a bad idea?
![comment](https://user-images.githubusercontent.com/29824802/64229735-41139080-cf08-11e9-94f2-6ce808072c52.JPG)
![errors](https://user-images.githubusercontent.com/29824802/64229744-4a9cf880-cf08-11e9-9ef0-4c31ccefab79.JPG)

**Comment by VincentTam** [comment]
> Unable to fix the error at the moment.

Your error is caused by the use of `api.staticman.net/v2`, which is reported in eduardoboucas/staticman#306.  Note that the bot @statimcanapp is no longer available, and that Staticman's v3 URL scheme has been up since eduardoboucas/staticman#219, which is *not* covered in the official documentation.



> Maybe Disqus is not such a bad idea?

Yes, Disqus is a bad idea.

Disqus contains a 3rd-party script to be loaded during page rendering. The code block for loading it shows that the static comments are not rendered as static HTML code. This hinders search engines from grabbing the comments, which are part of the site's content.

To see more reasons for migrating from Disqus, you may view

1. https://victorzhou.com/blog/replacing-disqus/
1. https://old.reddit.com/r/programming/comments/b9022a/switching_off_of_disqus_reduced_my_page_weight_by/
1. https://medium.com/remys-blog/ejecting-disqus-4120e9985823

You may avoid these problems by switching to [Staticman](https://staticman.net), which makes use of GitHub/GitLab Pull/Merge Requests instead of issues. Under Staticman's model, static comments are YML/JSON files stored in the remote GitHub/GitLab repo (usually under data/comments, configurable through the path parameter in root-level staticman.yml), and through a static blog generator (Jekyll/Hugo/etc), the stored data are rendered as part of the content. This gives a total ownership of a static site's comments.

**Comment by thisHermit** [comment]
Thanks a lot @VincentTam , fixed the form. Migrated the comments functionality to a new branch for now.
